apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      containers:
      - name: web-server
        image: demo-web-server:effd547897b1cc03cfe98213a375e8be04e97a39
        ports:
        - containerPort: 8443
          protocol: TCP
        volumeMounts:
        - name: tls-certs
          mountPath: "/etc/tls"
          readOnly: true
      volumes:
      - name: tls-certs
        secret: 
          secretName: my-tls-secret